export const ALLOWED_FLOWS = [
  "DF_TRM_DAILY_LATEST",
  "DF_TRM_DAILY_HIST",
  "DF_CBR_DAILY_LATEST",
  "DF_CBR_DAILY_HIST",
  "DF_IR_DAILY_LATEST",
  "DF_IR_DAILY_HIST",
  "DF_COLCAP_MONTHLY_LATEST",
  "DF_COLCAP_MONTHLY_HIST",
  "DF_MONAGG_MONTHLY_LATEST",
  "DF_MONAGG_MONTHLY_HIST",
  "DF_UVR_DAILY_LATEST",
  "DF_UVR_DAILY_HIST",
] as const;

export type FlowId = (typeof ALLOWED_FLOWS)[number];
